name: Dev Release
on: [push, workflow_dispatch]

permissions:
  contents: write

env:
  BUILD_TYPE: Release
jobs:
  dev-release:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [stalker2_uevr]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{matrix.target}}

      - name: Prepare Release Structure
        run: |
          if (!(Test-Path "artifact/plugins")) { New-Item -Path "artifact/plugins" -ItemType Directory -Force }
          cp ${{github.workspace}}/build/${{env.BUILD_TYPE}}/stalker2_uevr.dll artifact/plugins/
          if (Test-Path "artifacts/*") { cp -r artifacts/* artifact/ }

      - name: Create Release Archive
        run: |
          7z a ${{github.workspace}}/Stalker2-Win64-Shipping.zip ./artifact/*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Stalker2-Win64-Shipping.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: Stalker2-Win64-Shipping
          path: ${{github.workspace}}/Stalker2-Win64-Shipping.zip
          if-no-files-found: error
